GET http://localhost:3001/

###
GET http://localhost:3001/songs

###
GET http://localhost:3001/songs/1

###
POST  http://localhost:3001/songs
Content-Type: application/json

{
    "title": "You and me",
    "artists": [1,2],
    "releasedDate": "2025-05-12",
    "duration": "02:34",
    "lyrics": "This thing is working"
}

###
PUT  http://localhost:3001/songs/1
Content-Type: application/json

{
    "title": "Eminem",
    "artists": ["Alan walker", "me"],
    "releasedDate": "2025-05-07",
    "duration": "02:34",
    "lyrics": "This thing is working"
}

###
DELETE   http://localhost:3001/songs/1

###
DELETE   http://localhost:3001/songs/reset

### Signup Artist
POST http://localhost:3001/auth/signup
Content-Type: application/json

{
"firstName": "Kachi",
"lastName": "Nerd",
"email": "kachinerd02@gmail.com",
"password": "123456"
}

### Login Artist
POST http://localhost:3001/auth/login
Content-Type: application/json

{
"email": "kachinerd02@gmail.com",
"password": "123456"
}

## access token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImthY2hpbmVyZDAyQGdtYWlsLmNvbSIsInVzZXJJZCI6MTQsImlhdCI6MTc0ODAyOTc4NCwiZXhwIjoxNzQ4MTE2MTg0fQ.cFr0CPkoSx95j6L56VS2wc9DhRxOWLBFvXA9FuanNtE

### Profile
GET http://localhost:3001/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImthY2hpbmVyZDAyQGdtYWlsLmNvbSIsInVzZXJJZCI6MTQsImlhdCI6MTc0ODAyOTc4NCwiZXhwIjoxNzQ4MTE2MTg0fQ.cFr0CPkoSx95j6L56VS2wc9DhRxOWLBFvXA9FuanNtE

