GET http://localhost:3001/songs

###
GET http://localhost:3001/songs/3

###
POST  http://localhost:3001/songs
Content-Type: application/json

{
    "title": "Alan walker",
    "artists": ["Alan walker"],
    "releaseDate": "2025-05-07",
    "duration": "02:34"
}

###
PUT  http://localhost:3001/songs/1

###
DELETE   http://localhost:3001/songs/1

